server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-exception: false      # Response 에 Exception 을 표시할지 (오류 응답에 exception의 내용을 포함할지 여부)
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

spring:
  application:
    name: deuk-lab
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      static-path-pattern: /resources/**
    pathmatch:
      matching-strategy: ant_path_matcher #swagger3 적용을 위한 설정
  message:
    basename: classpath:/messages/message
    cache-duration: 60
    encoding: UTF-8

mybatis:
  configuration:
    lazy-loading-enabled: false
    default-statement-timeout: 25
    map-underscore-to-camel-case: false
    jdbc-type-for-null: "null"
    call-setters-on-nulls: true
  mapper-locations: classpath:db/*.xml
  type-aliases-package: com.sktel.nscan.adapters.database

logging:
  config: classpath:config/log/logback-${spring.profiles.active}.xml

management:
  endpoint:
    health:
      show-details: always

