server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-exception: false      # Response 에 Exception 을 표시할지 (오류 응답에 exception의 내용을 포함할지 여부)
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

spring:
  application:
    name: nscan-admin
  profiles:
    active: local
#  jsp적용시
  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#      static-path-pattern: /resources/**
    pathmatch:
      matching-strategy: ant_path_matcher #swagger3 적용을 위한 설정
# thymeleaf
  thymeleaf:
    enabled: true                     # thymeleaf 사용 여부
    encoding: UTF-8                   # template 인코딩
    cache: false                      # cache 활성화 여부, 개발환경에서는 비 활성화
    check-template-location: true     # 렌더링 전에 template 존재 여부 확인
    check-template=true: true         # template 위치 존재 여부 확인
    prefix: classpath:/templates/     # template 경로 접두사
    suffix: .html                     # template 경로 접미사
    mode: HTML                        #기본 template 모드, TemplateMode에 정의 (HTML, XML, TEXT, JAVASCRIPT 등)
  message:
    basename: classpath:/messages/message
    cache-duration: 60
    encoding: UTF-8

mybatis:
  configuration:
    lazy-loading-enabled: false
    default-statement-timeout: 25
    map-underscore-to-camel-case: false
    jdbc-type-for-null: "null"
    call-setters-on-nulls: true
  mapper-locations: classpath:db/*.xml
  type-aliases-package: com.sktel.nscan.adapters.database

logging:
  config: classpath:config/log/logback-${spring.profiles.active}.xml

management:
  endpoint:
    health:
      show-details: always

